name = input("Hey! What's your name? ")
print(name, "This is the first story!")
print("")

a1 = input("Enter an adjective: ")
city = input("Enter the name of a city: ")
a2 = input("Enter an adjective (capitalize the first letter): ")
n1 = input("Enter a noun (capitalize the first letter): ")
v1 = input("Enter a verb (capitalize the first letter): ")
animal = input("Enter an animal species: ")
n2 = input("Enter a noun (capitalize the first letter): ")
a3 = input("Enter an adjective: ")
sound = input("Enter a kind of sound (e.g. hiss): ")
v2 = input("Enter a verb: ")
time = input("Enter a time of day: ")
song = input("Enter a song title: ")
v3 = input("Enter a verb: ")
accessory = input("Enter a kind of accessory: ")
exclamation = input("Enter an exclamatory phrase: ")
utensil = input("Enter a plural kitchen utensil: ")
v4 = input("Enter a verb: ")

print("")
print("That's all! Here's your story: ")
print("")

print("My mom is the most", a1, "detective in", city + "! Called the", a2, n1, "everyone knows her as the 'One to", v1, "all Crime'. But no one knows what she's truly like when it's just us two at home. She has a", animal, "who she calls", n2 + ". She thinks it's hilarious, but I think it's", a3 + ". The", animal, "loves to", sound, "every day and I hate it. My mom says", n2, "is for her detective work because it somehow helps her", v2 + ". If it were just", n2, "that would be okay with me. But there's so much more. Every day she wakes up at", time, "with her alarm clock blaring out the notes to '" + song + "' at the highest volume. She says it's to help her", v3 + ". Sometimes, my mom wears her favorite", accessory, "around the house and screams '" + exclamation + "' while brandishing our", utensil, "and running around the house. She says it's to help her", v4 + ". All these coincidences just don't add up. But that's just me thinking.")