name = input("Hey! What's your name? ")
print(name, "This is the first story!")
print("")

a1 = input("Enter an adjective: ")
a2 = input("Enter an adjective: ")
place1 = input("Enter a location: ")
a3 = input("Enter an adjective: ")
a4 = input("Enter an adjective: ")
a5 = input("Enter an adjective (capitalize the first letter): ")
n1 = input("Enter a noun (capitalize the first letter): ")
animal = input("Enter an animal species: ")
name1 = input("Enter a name (capitalize the first letter): ")
place2 = input("Enter a location: ")
a6 = input("Enter an adjective (capitalize the first letter): ")
n2 = input("Enter a noun (capitalize the first letter): ")
a7 = input("Enter an adjective (capitalize the first letter): ")
n3 = input("Enter a noun (capitalize the first letter): ")
v1 = input("Enter a verb: ")
clothing = input("Enter a kind of clothing item: ")
a8 = input("Enter an adjective: ")
accessory = input("Enter a kind of accessory: ")
superpower1 = input("Enter a superpower: ")
superpower2 = input("Enter a different superpower: ")
insect = input("Enter a kind of insect: ")
body1 = input("Enter a body part: ")
ving1 = input("Enter a verb that ends in -ing: ")
ving2 = input("Enter a verb that ends in -ing: ")
body2 = input("Enter a body part: ")
idea = input("Enter an idea or concept: ")

print("")
print("That's all! Here's your story: ")
print("")

print("I am secretly a superhero. I know. It's so weird. Normal people know me as just", a1, a2, "and that one person who works at the", place1 + ". People from high school would call me", a3, "and my parents would call me", a4 + ". So a nobody really. But no one knows about my double life as the", a5, n1 + ", also known as just", a5 + ". Well except for my pet", animal + ",", name1, ", who lives in my", place2 + ". He can talk and gives me advice on how to fight villains such as the", a6, n2, "or the", a7, n3 + ". Mostly he just likes to", v1, "though. Anyway, every week, I head out in my", clothing, "and", a8, accessory, "and fight crime! It's so fun. I have the ability to", superpower1, "and", superpower2, "after a mysterious", insect, "bit me in the", body1 + ". I love", ving1, "my enemies in the", body1, "and", ving2, "them in the", body2 + ". It's all for my mission to spread", idea, "to the city, after all.")