name = input("Hey! What's your name? ")
print(name, "This is the first story!")
print("")

adjective1 = input("Enter an adjective: ")
noun1 = input("Enter a noun (capitalize the first letter): ")
adjective2 = input("Enter an adjective: ")
pluralnoun1 = input("Enter a plural noun: ")
noun2 = input("Enter a noun (capitalize the first letter): ")
name1 = input("Enter a name (capitalize the first letter): ")
noun3 = input("Enter a noun: ")
name2 = input("Enter a name (capitalize the first letter): ")
noun4 = input("Enter a noun (capitalize the first letter): ")
verb1 = input("Enter a verb (capitalize the first letter): ")
place1 = input("Enter a location: ")
adjective3 = input("Enter an adjective (capitalize the first letter): ")
noun5 = input("Enter a noun (capitalize the first letter): ")
pluralnoun2 = input("Enter a plural noun: ")
name3 = input("Enter a name (capitalize the first letter): ")
pluralnoun3 = input("Enter a plural noun: ")
number1 = str(input("Enter a number: "))
adjective4 = input("Enter an adjective: ")
adjective5 = input("Enter an adjective: ")
pluralnoun4 = input("Enter a plural noun: ")

print("")
print("That's all! Here's your story: ")
print("")

print("I'm so", adjective1 + ". Today, I start my first day at", noun1, "High School! Known for its", adjective2, pluralnoun1, "and extremely fulfilling", noun2, "Program, this high school is hard to beat. There's some weird things about this school though too. Ms.", name1, "is known for teaching with her", noun3, "and rambling about her new pet,", name2 + ". Mr.", noun4 + ", the head of the", verb1, "Department, can be found all day in the", place1, "instead of doing work in his office. Some students remind us new freshmen about the Great", adjective3, noun5, "Incident, where a group of", pluralnoun2, "stormed the school and asked the principal, Mr.", name3, "to give them all his", pluralnoun3 + ". Apparently almost", number1, "principals have been threatened by this", adjective4, "group! But other than that this school is pretty normal. All the students are", adjective5, "and love playing with their", pluralnoun4 + ". I'm so", adjective1, "to attend!")